title: "Project Hub"
description: "A central index of all my GitHub projects organized by topic."

theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

